version: '3'

services:
  rest-api:
    build: .
    container_name: rest-api
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - rest-api-network
    depends_on:
      - pgsql
  pgsql:
    image: postgres:latest
    container_name: pgsql
    ports:
      - '5432:5432'
    networks:
      - rest-api-network
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rest-api
    networks:
      - rest-api-network
networks:
  rest-api-network:
    name: rest-api-network
    driver: bridge
