// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Books []*Books `json:"books,omitempty"`
}

type Books struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	Categories  []*Category `json:"categories,omitempty"`
}

type Category struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Books       []*Books `json:"books,omitempty"`
}

type NewAuthor struct {
	Name string `json:"name"`
}

type NewBook struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Categories  []string `json:"categories,omitempty"`
}

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}
